# Usa imagem Python oficial
FROM python:3.11-slim

# Define diretório de trabalho
WORKDIR /app

# Copia tudo
COPY . /app

# Instala dependências
RUN pip install --no-cache-dir -r requirements.txt

# Expõe a porta exigida pelo Cloud Run
EXPOSE 8080

# Comando para iniciar o Functions Framework
CMD ["functions-framework", "--target=analisar_pta", "--port=8080"]
